// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: exercise.proto

package exercise

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExerciseService_ExerciseExistsReturnId_FullMethodName               = "/exercise.ExerciseService/ExerciseExistsReturnId"
	ExerciseService_ExerciseExistsInMainReturnEveryThing_FullMethodName = "/exercise.ExerciseService/ExerciseExistsInMainReturnEveryThing"
	ExerciseService_GetExerciseName_FullMethodName                      = "/exercise.ExerciseService/GetExerciseName"
	ExerciseService_GetAllExercises_FullMethodName                      = "/exercise.ExerciseService/GetAllExercises"
	ExerciseService_GetOneExercise_FullMethodName                       = "/exercise.ExerciseService/GetOneExercise"
	ExerciseService_CreateExercise_FullMethodName                       = "/exercise.ExerciseService/CreateExercise"
	ExerciseService_DeleteExercise_FullMethodName                       = "/exercise.ExerciseService/DeleteExercise"
	ExerciseService_PING_FullMethodName                                 = "/exercise.ExerciseService/PING"
	ExerciseService_GetHealth_FullMethodName                            = "/exercise.ExerciseService/GetHealth"
)

// ExerciseServiceClient is the client API for ExerciseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExerciseServiceClient interface {
	// used by plan service
	ExerciseExistsReturnId(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*ExerciseExistsReturnIdResp, error)
	ExerciseExistsInMainReturnEveryThing(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*SendEverythingResp, error)
	// used by plan service
	GetExerciseName(ctx context.Context, in *SendExerciseID, opts ...grpc.CallOption) (*GetExerciseNameResp, error)
	GetAllExercises(ctx context.Context, in *GetAllExercisesREq, opts ...grpc.CallOption) (*GetAllExercisesResp, error)
	GetOneExercise(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*OneExerciseResp, error)
	CreateExercise(ctx context.Context, in *CreateExerciseReq, opts ...grpc.CallOption) (*CreateExerciseResp, error)
	// rpc UpdateExercise() returns () {};
	DeleteExercise(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*DeleteExerciseResp, error)
	PING(ctx context.Context, in *PingExerReq, opts ...grpc.CallOption) (*PingExerResp, error)
	GetHealth(ctx context.Context, in *GetHealthReq, opts ...grpc.CallOption) (*GetHealthResp, error)
}

type exerciseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExerciseServiceClient(cc grpc.ClientConnInterface) ExerciseServiceClient {
	return &exerciseServiceClient{cc}
}

func (c *exerciseServiceClient) ExerciseExistsReturnId(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*ExerciseExistsReturnIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseExistsReturnIdResp)
	err := c.cc.Invoke(ctx, ExerciseService_ExerciseExistsReturnId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) ExerciseExistsInMainReturnEveryThing(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*SendEverythingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEverythingResp)
	err := c.cc.Invoke(ctx, ExerciseService_ExerciseExistsInMainReturnEveryThing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetExerciseName(ctx context.Context, in *SendExerciseID, opts ...grpc.CallOption) (*GetExerciseNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExerciseNameResp)
	err := c.cc.Invoke(ctx, ExerciseService_GetExerciseName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetAllExercises(ctx context.Context, in *GetAllExercisesREq, opts ...grpc.CallOption) (*GetAllExercisesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllExercisesResp)
	err := c.cc.Invoke(ctx, ExerciseService_GetAllExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetOneExercise(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*OneExerciseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OneExerciseResp)
	err := c.cc.Invoke(ctx, ExerciseService_GetOneExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) CreateExercise(ctx context.Context, in *CreateExerciseReq, opts ...grpc.CallOption) (*CreateExerciseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExerciseResp)
	err := c.cc.Invoke(ctx, ExerciseService_CreateExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) DeleteExercise(ctx context.Context, in *SendExerciseName, opts ...grpc.CallOption) (*DeleteExerciseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExerciseResp)
	err := c.cc.Invoke(ctx, ExerciseService_DeleteExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) PING(ctx context.Context, in *PingExerReq, opts ...grpc.CallOption) (*PingExerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingExerResp)
	err := c.cc.Invoke(ctx, ExerciseService_PING_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetHealth(ctx context.Context, in *GetHealthReq, opts ...grpc.CallOption) (*GetHealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResp)
	err := c.cc.Invoke(ctx, ExerciseService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseServiceServer is the server API for ExerciseService service.
// All implementations must embed UnimplementedExerciseServiceServer
// for forward compatibility.
type ExerciseServiceServer interface {
	// used by plan service
	ExerciseExistsReturnId(context.Context, *SendExerciseName) (*ExerciseExistsReturnIdResp, error)
	ExerciseExistsInMainReturnEveryThing(context.Context, *SendExerciseName) (*SendEverythingResp, error)
	// used by plan service
	GetExerciseName(context.Context, *SendExerciseID) (*GetExerciseNameResp, error)
	GetAllExercises(context.Context, *GetAllExercisesREq) (*GetAllExercisesResp, error)
	GetOneExercise(context.Context, *SendExerciseName) (*OneExerciseResp, error)
	CreateExercise(context.Context, *CreateExerciseReq) (*CreateExerciseResp, error)
	// rpc UpdateExercise() returns () {};
	DeleteExercise(context.Context, *SendExerciseName) (*DeleteExerciseResp, error)
	PING(context.Context, *PingExerReq) (*PingExerResp, error)
	GetHealth(context.Context, *GetHealthReq) (*GetHealthResp, error)
	mustEmbedUnimplementedExerciseServiceServer()
}

// UnimplementedExerciseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExerciseServiceServer struct{}

func (UnimplementedExerciseServiceServer) ExerciseExistsReturnId(context.Context, *SendExerciseName) (*ExerciseExistsReturnIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExerciseExistsReturnId not implemented")
}
func (UnimplementedExerciseServiceServer) ExerciseExistsInMainReturnEveryThing(context.Context, *SendExerciseName) (*SendEverythingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExerciseExistsInMainReturnEveryThing not implemented")
}
func (UnimplementedExerciseServiceServer) GetExerciseName(context.Context, *SendExerciseID) (*GetExerciseNameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExerciseName not implemented")
}
func (UnimplementedExerciseServiceServer) GetAllExercises(context.Context, *GetAllExercisesREq) (*GetAllExercisesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllExercises not implemented")
}
func (UnimplementedExerciseServiceServer) GetOneExercise(context.Context, *SendExerciseName) (*OneExerciseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOneExercise not implemented")
}
func (UnimplementedExerciseServiceServer) CreateExercise(context.Context, *CreateExerciseReq) (*CreateExerciseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExercise not implemented")
}
func (UnimplementedExerciseServiceServer) DeleteExercise(context.Context, *SendExerciseName) (*DeleteExerciseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExercise not implemented")
}
func (UnimplementedExerciseServiceServer) PING(context.Context, *PingExerReq) (*PingExerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PING not implemented")
}
func (UnimplementedExerciseServiceServer) GetHealth(context.Context, *GetHealthReq) (*GetHealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedExerciseServiceServer) mustEmbedUnimplementedExerciseServiceServer() {}
func (UnimplementedExerciseServiceServer) testEmbeddedByValue()                         {}

// UnsafeExerciseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExerciseServiceServer will
// result in compilation errors.
type UnsafeExerciseServiceServer interface {
	mustEmbedUnimplementedExerciseServiceServer()
}

func RegisterExerciseServiceServer(s grpc.ServiceRegistrar, srv ExerciseServiceServer) {
	// If the following call panics, it indicates UnimplementedExerciseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExerciseService_ServiceDesc, srv)
}

func _ExerciseService_ExerciseExistsReturnId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExerciseName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).ExerciseExistsReturnId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_ExerciseExistsReturnId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).ExerciseExistsReturnId(ctx, req.(*SendExerciseName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_ExerciseExistsInMainReturnEveryThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExerciseName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).ExerciseExistsInMainReturnEveryThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_ExerciseExistsInMainReturnEveryThing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).ExerciseExistsInMainReturnEveryThing(ctx, req.(*SendExerciseName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetExerciseName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExerciseID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExerciseName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExerciseName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExerciseName(ctx, req.(*SendExerciseID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetAllExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllExercisesREq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetAllExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetAllExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetAllExercises(ctx, req.(*GetAllExercisesREq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetOneExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExerciseName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetOneExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetOneExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetOneExercise(ctx, req.(*SendExerciseName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_CreateExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExerciseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).CreateExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_CreateExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).CreateExercise(ctx, req.(*CreateExerciseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_DeleteExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExerciseName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).DeleteExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_DeleteExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).DeleteExercise(ctx, req.(*SendExerciseName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_PING_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingExerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).PING(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_PING_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).PING(ctx, req.(*PingExerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetHealth(ctx, req.(*GetHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ExerciseService_ServiceDesc is the grpc.ServiceDesc for ExerciseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExerciseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exercise.ExerciseService",
	HandlerType: (*ExerciseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExerciseExistsReturnId",
			Handler:    _ExerciseService_ExerciseExistsReturnId_Handler,
		},
		{
			MethodName: "ExerciseExistsInMainReturnEveryThing",
			Handler:    _ExerciseService_ExerciseExistsInMainReturnEveryThing_Handler,
		},
		{
			MethodName: "GetExerciseName",
			Handler:    _ExerciseService_GetExerciseName_Handler,
		},
		{
			MethodName: "GetAllExercises",
			Handler:    _ExerciseService_GetAllExercises_Handler,
		},
		{
			MethodName: "GetOneExercise",
			Handler:    _ExerciseService_GetOneExercise_Handler,
		},
		{
			MethodName: "CreateExercise",
			Handler:    _ExerciseService_CreateExercise_Handler,
		},
		{
			MethodName: "DeleteExercise",
			Handler:    _ExerciseService_DeleteExercise_Handler,
		},
		{
			MethodName: "PING",
			Handler:    _ExerciseService_PING_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _ExerciseService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exercise.proto",
}
