// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHealthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthReq) Reset() {
	*x = GetHealthReq{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthReq) ProtoMessage() {}

func (x *GetHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthReq.ProtoReflect.Descriptor instead.
func (*GetHealthReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type GetHealthResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PostgresRespTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=postgres_resp_time,json=postgresRespTime,proto3" json:"postgres_resp_time,omitempty"`
	RedisRespTime    *durationpb.Duration   `protobuf:"bytes,4,opt,name=redis_resp_time,json=redisRespTime,proto3" json:"redis_resp_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetHealthResp) Reset() {
	*x = GetHealthResp{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResp) ProtoMessage() {}

func (x *GetHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResp.ProtoReflect.Descriptor instead.
func (*GetHealthResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthResp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetHealthResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResp) GetPostgresRespTime() *durationpb.Duration {
	if x != nil {
		return x.PostgresRespTime
	}
	return nil
}

func (x *GetHealthResp) GetRedisRespTime() *durationpb.Duration {
	if x != nil {
		return x.RedisRespTime
	}
	return nil
}

type ChangeEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldEmail      string                 `protobuf:"bytes,2,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail      string                 `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmailReq) Reset() {
	*x = ChangeEmailReq{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailReq) ProtoMessage() {}

func (x *ChangeEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailReq.ProtoReflect.Descriptor instead.
func (*ChangeEmailReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeEmailReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeEmailReq) GetOldEmail() string {
	if x != nil {
		return x.OldEmail
	}
	return ""
}

func (x *ChangeEmailReq) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type ChangeEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmailResp) Reset() {
	*x = ChangeEmailResp{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailResp) ProtoMessage() {}

func (x *ChangeEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailResp.ProtoReflect.Descriptor instead.
func (*ChangeEmailResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChangePassReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPass       string                 `protobuf:"bytes,2,opt,name=old_pass,json=oldPass,proto3" json:"old_pass,omitempty"`
	NewPass       string                 `protobuf:"bytes,3,opt,name=new_pass,json=newPass,proto3" json:"new_pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePassReq) Reset() {
	*x = ChangePassReq{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePassReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePassReq) ProtoMessage() {}

func (x *ChangePassReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePassReq.ProtoReflect.Descriptor instead.
func (*ChangePassReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePassReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePassReq) GetOldPass() string {
	if x != nil {
		return x.OldPass
	}
	return ""
}

func (x *ChangePassReq) GetNewPass() string {
	if x != nil {
		return x.NewPass
	}
	return ""
}

type ChangePassResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePassResp) Reset() {
	*x = ChangePassResp{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePassResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePassResp) ProtoMessage() {}

func (x *ChangePassResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePassResp.ProtoReflect.Descriptor instead.
func (*ChangePassResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePassResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PINGreq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PINGreq) Reset() {
	*x = PINGreq{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PINGreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PINGreq) ProtoMessage() {}

func (x *PINGreq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PINGreq.ProtoReflect.Descriptor instead.
func (*PINGreq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

type PINGresp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PINGresp) Reset() {
	*x = PINGresp{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PINGresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PINGresp) ProtoMessage() {}

func (x *PINGresp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PINGresp.ProtoReflect.Descriptor instead.
func (*PINGresp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

type SendUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUUID) Reset() {
	*x = SendUUID{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUUID) ProtoMessage() {}

func (x *SendUUID) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUUID.ProtoReflect.Descriptor instead.
func (*SendUUID) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SendUUID) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type GetNewAccessTokenResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewAccessToken string                 `protobuf:"bytes,1,opt,name=new_access_token,json=newAccessToken,proto3" json:"new_access_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNewAccessTokenResp) Reset() {
	*x = GetNewAccessTokenResp{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewAccessTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAccessTokenResp) ProtoMessage() {}

func (x *GetNewAccessTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAccessTokenResp.ProtoReflect.Descriptor instead.
func (*GetNewAccessTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetNewAccessTokenResp) GetNewAccessToken() string {
	if x != nil {
		return x.NewAccessToken
	}
	return ""
}

type SendUserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserId) Reset() {
	*x = SendUserId{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserId) ProtoMessage() {}

func (x *SendUserId) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserId.ProtoReflect.Descriptor instead.
func (*SendUserId) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SendUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserLogOutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogOutResp) Reset() {
	*x = UserLogOutResp{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogOutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogOutResp) ProtoMessage() {}

func (x *UserLogOutResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogOutResp.ProtoReflect.Descriptor instead.
func (*UserLogOutResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *UserLogOutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *UserLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UUID          string                 `protobuf:"bytes,5,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResp) Reset() {
	*x = UserLoginResp{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResp) ProtoMessage() {}

func (x *UserLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResp.ProtoReflect.Descriptor instead.
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *UserLoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserLoginResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserLoginResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserLoginResp) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *UserLoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserSignUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignUpReq) Reset() {
	*x = UserSignUpReq{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpReq) ProtoMessage() {}

func (x *UserSignUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpReq.ProtoReflect.Descriptor instead.
func (*UserSignUpReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *UserSignUpReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSignUpReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUpReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSignUpReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserSignUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignUpResp) Reset() {
	*x = UserSignUpResp{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpResp) ProtoMessage() {}

func (x *UserSignUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpResp.ProtoReflect.Descriptor instead.
func (*UserSignUpResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *UserSignUpResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSignUpResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUpResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserSignUpResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserSignUpResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x0e\n" +
	"\fGetHealthReq\"\xd6\x01\n" +
	"\rGetHealthResp\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12G\n" +
	"\x12postgres_resp_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10postgresRespTime\x12A\n" +
	"\x0fredis_resp_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rredisRespTime\"c\n" +
	"\x0eChangeEmailReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\told_email\x18\x02 \x01(\tR\boldEmail\x12\x1b\n" +
	"\tnew_email\x18\x03 \x01(\tR\bnewEmail\"+\n" +
	"\x0fChangeEmailResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"^\n" +
	"\rChangePassReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bold_pass\x18\x02 \x01(\tR\aoldPass\x12\x19\n" +
	"\bnew_pass\x18\x03 \x01(\tR\anewPass\"*\n" +
	"\x0eChangePassResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\t\n" +
	"\aPINGreq\"\n" +
	"\n" +
	"\bPINGresp\"\x1e\n" +
	"\bSendUUID\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\"A\n" +
	"\x15GetNewAccessTokenResp\x12(\n" +
	"\x10new_access_token\x18\x01 \x01(\tR\x0enewAccessToken\"%\n" +
	"\n" +
	"SendUserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0eUserLogOutResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\fUserLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa3\x01\n" +
	"\rUserLoginResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04UUID\x18\x05 \x01(\tR\x04UUID\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"i\n" +
	"\rUserSignUpReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xa2\x01\n" +
	"\x0eUserSignUpResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId2\xd6\x03\n" +
	"\vAuthService\x129\n" +
	"\n" +
	"UserSignUp\x12\x13.auth.UserSignUpReq\x1a\x14.auth.UserSignUpResp\"\x00\x126\n" +
	"\tUserLogin\x12\x12.auth.UserLoginReq\x1a\x13.auth.UserLoginResp\"\x00\x126\n" +
	"\n" +
	"UserLogOut\x12\x10.auth.SendUserId\x1a\x14.auth.UserLogOutResp\"\x00\x12B\n" +
	"\x11GetNewAccessToken\x12\x0e.auth.SendUUID\x1a\x1b.auth.GetNewAccessTokenResp\"\x00\x12'\n" +
	"\x04PING\x12\r.auth.PINGreq\x1a\x0e.auth.PINGresp\"\x00\x129\n" +
	"\n" +
	"ChangePass\x12\x13.auth.ChangePassReq\x1a\x14.auth.ChangePassResp\"\x00\x12<\n" +
	"\vChangeEmail\x12\x14.auth.ChangeEmailReq\x1a\x15.auth.ChangeEmailResp\"\x00\x126\n" +
	"\tGetHealth\x12\x12.auth.GetHealthReq\x1a\x13.auth.GetHealthResp\"\x00B\x0eZ\f/shared/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_auth_proto_goTypes = []any{
	(*GetHealthReq)(nil),          // 0: auth.GetHealthReq
	(*GetHealthResp)(nil),         // 1: auth.GetHealthResp
	(*ChangeEmailReq)(nil),        // 2: auth.ChangeEmailReq
	(*ChangeEmailResp)(nil),       // 3: auth.ChangeEmailResp
	(*ChangePassReq)(nil),         // 4: auth.ChangePassReq
	(*ChangePassResp)(nil),        // 5: auth.ChangePassResp
	(*PINGreq)(nil),               // 6: auth.PINGreq
	(*PINGresp)(nil),              // 7: auth.PINGresp
	(*SendUUID)(nil),              // 8: auth.SendUUID
	(*GetNewAccessTokenResp)(nil), // 9: auth.GetNewAccessTokenResp
	(*SendUserId)(nil),            // 10: auth.SendUserId
	(*UserLogOutResp)(nil),        // 11: auth.UserLogOutResp
	(*UserLoginReq)(nil),          // 12: auth.UserLoginReq
	(*UserLoginResp)(nil),         // 13: auth.UserLoginResp
	(*UserSignUpReq)(nil),         // 14: auth.UserSignUpReq
	(*UserSignUpResp)(nil),        // 15: auth.UserSignUpResp
	(*durationpb.Duration)(nil),   // 16: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_auth_proto_depIdxs = []int32{
	16, // 0: auth.GetHealthResp.postgres_resp_time:type_name -> google.protobuf.Duration
	16, // 1: auth.GetHealthResp.redis_resp_time:type_name -> google.protobuf.Duration
	17, // 2: auth.UserSignUpResp.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: auth.AuthService.UserSignUp:input_type -> auth.UserSignUpReq
	12, // 4: auth.AuthService.UserLogin:input_type -> auth.UserLoginReq
	10, // 5: auth.AuthService.UserLogOut:input_type -> auth.SendUserId
	8,  // 6: auth.AuthService.GetNewAccessToken:input_type -> auth.SendUUID
	6,  // 7: auth.AuthService.PING:input_type -> auth.PINGreq
	4,  // 8: auth.AuthService.ChangePass:input_type -> auth.ChangePassReq
	2,  // 9: auth.AuthService.ChangeEmail:input_type -> auth.ChangeEmailReq
	0,  // 10: auth.AuthService.GetHealth:input_type -> auth.GetHealthReq
	15, // 11: auth.AuthService.UserSignUp:output_type -> auth.UserSignUpResp
	13, // 12: auth.AuthService.UserLogin:output_type -> auth.UserLoginResp
	11, // 13: auth.AuthService.UserLogOut:output_type -> auth.UserLogOutResp
	9,  // 14: auth.AuthService.GetNewAccessToken:output_type -> auth.GetNewAccessTokenResp
	7,  // 15: auth.AuthService.PING:output_type -> auth.PINGresp
	5,  // 16: auth.AuthService.ChangePass:output_type -> auth.ChangePassResp
	3,  // 17: auth.AuthService.ChangeEmail:output_type -> auth.ChangeEmailResp
	1,  // 18: auth.AuthService.GetHealth:output_type -> auth.GetHealthResp
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
