// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: plan.proto

package plan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlanByNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanName      string                 `protobuf:"bytes,1,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	ExerciseNames []string               `protobuf:"bytes,2,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	PlanId        string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByNameResp) Reset() {
	*x = GetPlanByNameResp{}
	mi := &file_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByNameResp) ProtoMessage() {}

func (x *GetPlanByNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByNameResp.ProtoReflect.Descriptor instead.
func (*GetPlanByNameResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlanByNameResp) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *GetPlanByNameResp) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

func (x *GetPlanByNameResp) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type GetHealthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthReq) Reset() {
	*x = GetHealthReq{}
	mi := &file_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthReq) ProtoMessage() {}

func (x *GetHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthReq.ProtoReflect.Descriptor instead.
func (*GetHealthReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{1}
}

type GetHealthResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PostgresRespTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=postgres_resp_time,json=postgresRespTime,proto3" json:"postgres_resp_time,omitempty"`
	RedisRespTime    *durationpb.Duration   `protobuf:"bytes,4,opt,name=redis_resp_time,json=redisRespTime,proto3" json:"redis_resp_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetHealthResp) Reset() {
	*x = GetHealthResp{}
	mi := &file_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResp) ProtoMessage() {}

func (x *GetHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResp.ProtoReflect.Descriptor instead.
func (*GetHealthResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{2}
}

func (x *GetHealthResp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetHealthResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResp) GetPostgresRespTime() *durationpb.Duration {
	if x != nil {
		return x.PostgresRespTime
	}
	return nil
}

func (x *GetHealthResp) GetRedisRespTime() *durationpb.Duration {
	if x != nil {
		return x.RedisRespTime
	}
	return nil
}

type PingPlanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPlanReq) Reset() {
	*x = PingPlanReq{}
	mi := &file_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPlanReq) ProtoMessage() {}

func (x *PingPlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPlanReq.ProtoReflect.Descriptor instead.
func (*PingPlanReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{3}
}

type PingPlanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPlanResp) Reset() {
	*x = PingPlanResp{}
	mi := &file_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPlanResp) ProtoMessage() {}

func (x *PingPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPlanResp.ProtoReflect.Descriptor instead.
func (*PingPlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{4}
}

type DeletePlanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanReq) Reset() {
	*x = DeletePlanReq{}
	mi := &file_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanReq) ProtoMessage() {}

func (x *DeletePlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanReq.ProtoReflect.Descriptor instead.
func (*DeletePlanReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePlanReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePlanReq) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

type DeletePlanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanResp) Reset() {
	*x = DeletePlanResp{}
	mi := &file_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanResp) ProtoMessage() {}

func (x *DeletePlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanResp.ProtoReflect.Descriptor instead.
func (*DeletePlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{6}
}

type PlanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	ExerciseNames []string               `protobuf:"bytes,3,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanReq) Reset() {
	*x = PlanReq{}
	mi := &file_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanReq) ProtoMessage() {}

func (x *PlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanReq.ProtoReflect.Descriptor instead.
func (*PlanReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{7}
}

func (x *PlanReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlanReq) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *PlanReq) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

type GetPlanByNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByNameReq) Reset() {
	*x = GetPlanByNameReq{}
	mi := &file_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByNameReq) ProtoMessage() {}

func (x *GetPlanByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByNameReq.ProtoReflect.Descriptor instead.
func (*GetPlanByNameReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlanByNameReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPlanByNameReq) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

type GetAllPlansReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPlansReq) Reset() {
	*x = GetAllPlansReq{}
	mi := &file_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPlansReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPlansReq) ProtoMessage() {}

func (x *GetAllPlansReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPlansReq.ProtoReflect.Descriptor instead.
func (*GetAllPlansReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllPlansReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllPlansResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfPlans int64                  `protobuf:"varint,1,opt,name=number_of_plans,json=numberOfPlans,proto3" json:"number_of_plans,omitempty"`
	AllPlans      []*PlanResp            `protobuf:"bytes,2,rep,name=all_plans,json=allPlans,proto3" json:"all_plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPlansResp) Reset() {
	*x = GetAllPlansResp{}
	mi := &file_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPlansResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPlansResp) ProtoMessage() {}

func (x *GetAllPlansResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPlansResp.ProtoReflect.Descriptor instead.
func (*GetAllPlansResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllPlansResp) GetNumberOfPlans() int64 {
	if x != nil {
		return x.NumberOfPlans
	}
	return 0
}

func (x *GetAllPlansResp) GetAllPlans() []*PlanResp {
	if x != nil {
		return x.AllPlans
	}
	return nil
}

type PlanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanName      string                 `protobuf:"bytes,1,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	ExerciseNames []string               `protobuf:"bytes,2,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResp) Reset() {
	*x = PlanResp{}
	mi := &file_plan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResp) ProtoMessage() {}

func (x *PlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResp.ProtoReflect.Descriptor instead.
func (*PlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{11}
}

func (x *PlanResp) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *PlanResp) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

type CreatePlanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	ExerciseNames []string               `protobuf:"bytes,3,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanReq) Reset() {
	*x = CreatePlanReq{}
	mi := &file_plan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanReq) ProtoMessage() {}

func (x *CreatePlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanReq.ProtoReflect.Descriptor instead.
func (*CreatePlanReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePlanReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePlanReq) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *CreatePlanReq) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

type CreatePlanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	ExerciseNames []string               `protobuf:"bytes,3,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanResp) Reset() {
	*x = CreatePlanResp{}
	mi := &file_plan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanResp) ProtoMessage() {}

func (x *CreatePlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanResp.ProtoReflect.Descriptor instead.
func (*CreatePlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePlanResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePlanResp) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *CreatePlanResp) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

type CheckHealthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthReq) Reset() {
	*x = CheckHealthReq{}
	mi := &file_plan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthReq) ProtoMessage() {}

func (x *CheckHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthReq.ProtoReflect.Descriptor instead.
func (*CheckHealthReq) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{14}
}

type CheckHealthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResp) Reset() {
	*x = CheckHealthResp{}
	mi := &file_plan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResp) ProtoMessage() {}

func (x *CheckHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResp.ProtoReflect.Descriptor instead.
func (*CheckHealthResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{15}
}

func (x *CheckHealthResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendUserID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserID) Reset() {
	*x = SendUserID{}
	mi := &file_plan_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserID) ProtoMessage() {}

func (x *SendUserID) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserID.ProtoReflect.Descriptor instead.
func (*SendUserID) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{16}
}

func (x *SendUserID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateEmptyPlanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmptyPlanResp) Reset() {
	*x = CreateEmptyPlanResp{}
	mi := &file_plan_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmptyPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmptyPlanResp) ProtoMessage() {}

func (x *CreateEmptyPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmptyPlanResp.ProtoReflect.Descriptor instead.
func (*CreateEmptyPlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{17}
}

func (x *CreateEmptyPlanResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyPlanIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmptyPlanId   string                 `protobuf:"bytes,1,opt,name=empty_plan_id,json=emptyPlanId,proto3" json:"empty_plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPlanIdResp) Reset() {
	*x = EmptyPlanIdResp{}
	mi := &file_plan_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPlanIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPlanIdResp) ProtoMessage() {}

func (x *EmptyPlanIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPlanIdResp.ProtoReflect.Descriptor instead.
func (*EmptyPlanIdResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{18}
}

func (x *EmptyPlanIdResp) GetEmptyPlanId() string {
	if x != nil {
		return x.EmptyPlanId
	}
	return ""
}

type SendPlanName struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlanName) Reset() {
	*x = SendPlanName{}
	mi := &file_plan_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlanName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlanName) ProtoMessage() {}

func (x *SendPlanName) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlanName.ProtoReflect.Descriptor instead.
func (*SendPlanName) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{19}
}

func (x *SendPlanName) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendPlanName) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

type PlanExistsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PlanId        int64                  `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExistsResp) Reset() {
	*x = PlanExistsResp{}
	mi := &file_plan_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExistsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExistsResp) ProtoMessage() {}

func (x *PlanExistsResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExistsResp.ProtoReflect.Descriptor instead.
func (*PlanExistsResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{20}
}

func (x *PlanExistsResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *PlanExistsResp) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type PlanExistsReturnPlanResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PlanId string `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	ExerciseIds   []string `protobuf:"bytes,3,rep,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExistsReturnPlanResp) Reset() {
	*x = PlanExistsReturnPlanResp{}
	mi := &file_plan_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExistsReturnPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExistsReturnPlanResp) ProtoMessage() {}

func (x *PlanExistsReturnPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExistsReturnPlanResp.ProtoReflect.Descriptor instead.
func (*PlanExistsReturnPlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{21}
}

func (x *PlanExistsReturnPlanResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *PlanExistsReturnPlanResp) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanExistsReturnPlanResp) GetExerciseIds() []string {
	if x != nil {
		return x.ExerciseIds
	}
	return nil
}

var File_plan_proto protoreflect.FileDescriptor

const file_plan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"plan.proto\x12\x04plan\x1a\x1egoogle/protobuf/duration.proto\"p\n" +
	"\x11GetPlanByNameResp\x12\x1b\n" +
	"\tplan_name\x18\x01 \x01(\tR\bplanName\x12%\n" +
	"\x0eexercise_names\x18\x02 \x03(\tR\rexerciseNames\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\"\x0e\n" +
	"\fGetHealthReq\"\xd6\x01\n" +
	"\rGetHealthResp\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12G\n" +
	"\x12postgres_resp_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10postgresRespTime\x12A\n" +
	"\x0fredis_resp_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rredisRespTime\"\r\n" +
	"\vPingPlanReq\"\x0e\n" +
	"\fPingPlanResp\"E\n" +
	"\rDeletePlanReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\"\x10\n" +
	"\x0eDeletePlanResp\"f\n" +
	"\aPlanReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12%\n" +
	"\x0eexercise_names\x18\x03 \x03(\tR\rexerciseNames\"H\n" +
	"\x10GetPlanByNameReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\")\n" +
	"\x0eGetAllPlansReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"f\n" +
	"\x0fGetAllPlansResp\x12&\n" +
	"\x0fnumber_of_plans\x18\x01 \x01(\x03R\rnumberOfPlans\x12+\n" +
	"\tall_plans\x18\x02 \x03(\v2\x0e.plan.PlanRespR\ballPlans\"N\n" +
	"\bPlanResp\x12\x1b\n" +
	"\tplan_name\x18\x01 \x01(\tR\bplanName\x12%\n" +
	"\x0eexercise_names\x18\x02 \x03(\tR\rexerciseNames\"l\n" +
	"\rCreatePlanReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12%\n" +
	"\x0eexercise_names\x18\x03 \x03(\tR\rexerciseNames\"n\n" +
	"\x0eCreatePlanResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12%\n" +
	"\x0eexercise_names\x18\x03 \x03(\tR\rexerciseNames\"\x10\n" +
	"\x0eCheckHealthReq\"+\n" +
	"\x0fCheckHealthResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\n" +
	"SendUserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x13CreateEmptyPlanResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"5\n" +
	"\x0fEmptyPlanIdResp\x12\"\n" +
	"\rempty_plan_id\x18\x01 \x01(\tR\vemptyPlanId\"D\n" +
	"\fSendPlanName\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\"A\n" +
	"\x0ePlanExistsResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x03R\x06planId\"n\n" +
	"\x18PlanExistsReturnPlanResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12!\n" +
	"\fexercise_ids\x18\x03 \x03(\tR\vexerciseIds2\xae\x06\n" +
	"\vPlanService\x12@\n" +
	"\x12PlanExistsReturnId\x12\x12.plan.SendPlanName\x1a\x14.plan.PlanExistsResp\"\x00\x12L\n" +
	"\x14PlanExistsReturnPlan\x12\x12.plan.SendPlanName\x1a\x1e.plan.PlanExistsReturnPlanResp\"\x00\x12;\n" +
	"\x0eGetEmptyPlanId\x12\x10.plan.SendUserID\x1a\x15.plan.EmptyPlanIdResp\"\x00\x12@\n" +
	"\x0fCreateEmptyPlan\x12\x10.plan.SendUserID\x1a\x19.plan.CreateEmptyPlanResp\"\x00\x12<\n" +
	"\vCheckHealth\x12\x14.plan.CheckHealthReq\x1a\x15.plan.CheckHealthResp\"\x00\x129\n" +
	"\n" +
	"CreatePlan\x12\x13.plan.CreatePlanReq\x1a\x14.plan.CreatePlanResp\"\x00\x12<\n" +
	"\vGetAllPlans\x12\x14.plan.GetAllPlansReq\x1a\x15.plan.GetAllPlansResp\"\x00\x12B\n" +
	"\rGetPlanByName\x12\x16.plan.GetPlanByNameReq\x1a\x17.plan.GetPlanByNameResp\"\x00\x125\n" +
	"\x12AddExercisesToPlan\x12\r.plan.PlanReq\x1a\x0e.plan.PlanResp\"\x00\x12:\n" +
	"\x17DeleteExercisesFromPlan\x12\r.plan.PlanReq\x1a\x0e.plan.PlanResp\"\x00\x129\n" +
	"\n" +
	"DeletePlan\x12\x13.plan.DeletePlanReq\x1a\x14.plan.DeletePlanResp\"\x00\x12/\n" +
	"\x04PING\x12\x11.plan.PingPlanReq\x1a\x12.plan.PingPlanResp\"\x00\x126\n" +
	"\tGetHealth\x12\x12.plan.GetHealthReq\x1a\x13.plan.GetHealthResp\"\x00B\x0eZ\f/shared/planb\x06proto3"

var (
	file_plan_proto_rawDescOnce sync.Once
	file_plan_proto_rawDescData []byte
)

func file_plan_proto_rawDescGZIP() []byte {
	file_plan_proto_rawDescOnce.Do(func() {
		file_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)))
	})
	return file_plan_proto_rawDescData
}

var file_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_plan_proto_goTypes = []any{
	(*GetPlanByNameResp)(nil),        // 0: plan.GetPlanByNameResp
	(*GetHealthReq)(nil),             // 1: plan.GetHealthReq
	(*GetHealthResp)(nil),            // 2: plan.GetHealthResp
	(*PingPlanReq)(nil),              // 3: plan.PingPlanReq
	(*PingPlanResp)(nil),             // 4: plan.PingPlanResp
	(*DeletePlanReq)(nil),            // 5: plan.DeletePlanReq
	(*DeletePlanResp)(nil),           // 6: plan.DeletePlanResp
	(*PlanReq)(nil),                  // 7: plan.PlanReq
	(*GetPlanByNameReq)(nil),         // 8: plan.GetPlanByNameReq
	(*GetAllPlansReq)(nil),           // 9: plan.GetAllPlansReq
	(*GetAllPlansResp)(nil),          // 10: plan.GetAllPlansResp
	(*PlanResp)(nil),                 // 11: plan.PlanResp
	(*CreatePlanReq)(nil),            // 12: plan.CreatePlanReq
	(*CreatePlanResp)(nil),           // 13: plan.CreatePlanResp
	(*CheckHealthReq)(nil),           // 14: plan.CheckHealthReq
	(*CheckHealthResp)(nil),          // 15: plan.CheckHealthResp
	(*SendUserID)(nil),               // 16: plan.SendUserID
	(*CreateEmptyPlanResp)(nil),      // 17: plan.CreateEmptyPlanResp
	(*EmptyPlanIdResp)(nil),          // 18: plan.EmptyPlanIdResp
	(*SendPlanName)(nil),             // 19: plan.SendPlanName
	(*PlanExistsResp)(nil),           // 20: plan.PlanExistsResp
	(*PlanExistsReturnPlanResp)(nil), // 21: plan.PlanExistsReturnPlanResp
	(*durationpb.Duration)(nil),      // 22: google.protobuf.Duration
}
var file_plan_proto_depIdxs = []int32{
	22, // 0: plan.GetHealthResp.postgres_resp_time:type_name -> google.protobuf.Duration
	22, // 1: plan.GetHealthResp.redis_resp_time:type_name -> google.protobuf.Duration
	11, // 2: plan.GetAllPlansResp.all_plans:type_name -> plan.PlanResp
	19, // 3: plan.PlanService.PlanExistsReturnId:input_type -> plan.SendPlanName
	19, // 4: plan.PlanService.PlanExistsReturnPlan:input_type -> plan.SendPlanName
	16, // 5: plan.PlanService.GetEmptyPlanId:input_type -> plan.SendUserID
	16, // 6: plan.PlanService.CreateEmptyPlan:input_type -> plan.SendUserID
	14, // 7: plan.PlanService.CheckHealth:input_type -> plan.CheckHealthReq
	12, // 8: plan.PlanService.CreatePlan:input_type -> plan.CreatePlanReq
	9,  // 9: plan.PlanService.GetAllPlans:input_type -> plan.GetAllPlansReq
	8,  // 10: plan.PlanService.GetPlanByName:input_type -> plan.GetPlanByNameReq
	7,  // 11: plan.PlanService.AddExercisesToPlan:input_type -> plan.PlanReq
	7,  // 12: plan.PlanService.DeleteExercisesFromPlan:input_type -> plan.PlanReq
	5,  // 13: plan.PlanService.DeletePlan:input_type -> plan.DeletePlanReq
	3,  // 14: plan.PlanService.PING:input_type -> plan.PingPlanReq
	1,  // 15: plan.PlanService.GetHealth:input_type -> plan.GetHealthReq
	20, // 16: plan.PlanService.PlanExistsReturnId:output_type -> plan.PlanExistsResp
	21, // 17: plan.PlanService.PlanExistsReturnPlan:output_type -> plan.PlanExistsReturnPlanResp
	18, // 18: plan.PlanService.GetEmptyPlanId:output_type -> plan.EmptyPlanIdResp
	17, // 19: plan.PlanService.CreateEmptyPlan:output_type -> plan.CreateEmptyPlanResp
	15, // 20: plan.PlanService.CheckHealth:output_type -> plan.CheckHealthResp
	13, // 21: plan.PlanService.CreatePlan:output_type -> plan.CreatePlanResp
	10, // 22: plan.PlanService.GetAllPlans:output_type -> plan.GetAllPlansResp
	0,  // 23: plan.PlanService.GetPlanByName:output_type -> plan.GetPlanByNameResp
	11, // 24: plan.PlanService.AddExercisesToPlan:output_type -> plan.PlanResp
	11, // 25: plan.PlanService.DeleteExercisesFromPlan:output_type -> plan.PlanResp
	6,  // 26: plan.PlanService.DeletePlan:output_type -> plan.DeletePlanResp
	4,  // 27: plan.PlanService.PING:output_type -> plan.PingPlanResp
	2,  // 28: plan.PlanService.GetHealth:output_type -> plan.GetHealthResp
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plan_proto_init() }
func file_plan_proto_init() {
	if File_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plan_proto_goTypes,
		DependencyIndexes: file_plan_proto_depIdxs,
		MessageInfos:      file_plan_proto_msgTypes,
	}.Build()
	File_plan_proto = out.File
	file_plan_proto_goTypes = nil
	file_plan_proto_depIdxs = nil
}
