// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: plan.proto

package plan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlanService_PlanExistsReturnId_FullMethodName      = "/plan.PlanService/PlanExistsReturnId"
	PlanService_PlanExistsReturnPlan_FullMethodName    = "/plan.PlanService/PlanExistsReturnPlan"
	PlanService_GetEmptyPlanId_FullMethodName          = "/plan.PlanService/GetEmptyPlanId"
	PlanService_CreateEmptyPlan_FullMethodName         = "/plan.PlanService/CreateEmptyPlan"
	PlanService_CheckHealth_FullMethodName             = "/plan.PlanService/CheckHealth"
	PlanService_CreatePlan_FullMethodName              = "/plan.PlanService/CreatePlan"
	PlanService_GetAllPlans_FullMethodName             = "/plan.PlanService/GetAllPlans"
	PlanService_GetPlanByName_FullMethodName           = "/plan.PlanService/GetPlanByName"
	PlanService_AddExercisesToPlan_FullMethodName      = "/plan.PlanService/AddExercisesToPlan"
	PlanService_DeleteExercisesFromPlan_FullMethodName = "/plan.PlanService/DeleteExercisesFromPlan"
	PlanService_DeletePlan_FullMethodName              = "/plan.PlanService/DeletePlan"
	PlanService_PING_FullMethodName                    = "/plan.PlanService/PING"
	PlanService_GetHealth_FullMethodName               = "/plan.PlanService/GetHealth"
)

// PlanServiceClient is the client API for PlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlanServiceClient interface {
	// plan_name, user_id -> exists, plan_id
	PlanExistsReturnId(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsResp, error)
	// plan_name, user_id -> exits, plan_id, exercise_ids
	PlanExistsReturnPlan(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsReturnPlanResp, error)
	// user_id -> empty_plan_id
	GetEmptyPlanId(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*EmptyPlanIdResp, error)
	// user_id -> msg
	CreateEmptyPlan(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*CreateEmptyPlanResp, error)
	// {} -> msg
	CheckHealth(ctx context.Context, in *CheckHealthReq, opts ...grpc.CallOption) (*CheckHealthResp, error)
	// user_id, plan_name, exercises_names -> msg, plan_name, exercises_name
	CreatePlan(ctx context.Context, in *CreatePlanReq, opts ...grpc.CallOption) (*CreatePlanResp, error)
	// user_id -> number_of_plans, [{plan_name, exercise_names}]
	GetAllPlans(ctx context.Context, in *GetAllPlansReq, opts ...grpc.CallOption) (*GetAllPlansResp, error)
	// user_id, plan_name -> plan_name, exercise_names
	GetPlanByName(ctx context.Context, in *GetPlanByNameReq, opts ...grpc.CallOption) (*GetPlanByNameResp, error)
	// user_id, plan_name, exercise_names -> plan_names, exercise_names
	AddExercisesToPlan(ctx context.Context, in *PlanReq, opts ...grpc.CallOption) (*PlanResp, error)
	// user_id, plan_name, exercise_names -> plan_names, exercise_names
	DeleteExercisesFromPlan(ctx context.Context, in *PlanReq, opts ...grpc.CallOption) (*PlanResp, error)
	// user_id, plan_name -> {}
	DeletePlan(ctx context.Context, in *DeletePlanReq, opts ...grpc.CallOption) (*DeletePlanResp, error)
	PING(ctx context.Context, in *PingPlanReq, opts ...grpc.CallOption) (*PingPlanResp, error)
	GetHealth(ctx context.Context, in *GetHealthReq, opts ...grpc.CallOption) (*GetHealthResp, error)
}

type planServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanServiceClient(cc grpc.ClientConnInterface) PlanServiceClient {
	return &planServiceClient{cc}
}

func (c *planServiceClient) PlanExistsReturnId(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanExistsResp)
	err := c.cc.Invoke(ctx, PlanService_PlanExistsReturnId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) PlanExistsReturnPlan(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsReturnPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanExistsReturnPlanResp)
	err := c.cc.Invoke(ctx, PlanService_PlanExistsReturnPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetEmptyPlanId(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*EmptyPlanIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyPlanIdResp)
	err := c.cc.Invoke(ctx, PlanService_GetEmptyPlanId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) CreateEmptyPlan(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*CreateEmptyPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEmptyPlanResp)
	err := c.cc.Invoke(ctx, PlanService_CreateEmptyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) CheckHealth(ctx context.Context, in *CheckHealthReq, opts ...grpc.CallOption) (*CheckHealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthResp)
	err := c.cc.Invoke(ctx, PlanService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) CreatePlan(ctx context.Context, in *CreatePlanReq, opts ...grpc.CallOption) (*CreatePlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanResp)
	err := c.cc.Invoke(ctx, PlanService_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetAllPlans(ctx context.Context, in *GetAllPlansReq, opts ...grpc.CallOption) (*GetAllPlansResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPlansResp)
	err := c.cc.Invoke(ctx, PlanService_GetAllPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetPlanByName(ctx context.Context, in *GetPlanByNameReq, opts ...grpc.CallOption) (*GetPlanByNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanByNameResp)
	err := c.cc.Invoke(ctx, PlanService_GetPlanByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) AddExercisesToPlan(ctx context.Context, in *PlanReq, opts ...grpc.CallOption) (*PlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResp)
	err := c.cc.Invoke(ctx, PlanService_AddExercisesToPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) DeleteExercisesFromPlan(ctx context.Context, in *PlanReq, opts ...grpc.CallOption) (*PlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResp)
	err := c.cc.Invoke(ctx, PlanService_DeleteExercisesFromPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) DeletePlan(ctx context.Context, in *DeletePlanReq, opts ...grpc.CallOption) (*DeletePlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlanResp)
	err := c.cc.Invoke(ctx, PlanService_DeletePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) PING(ctx context.Context, in *PingPlanReq, opts ...grpc.CallOption) (*PingPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingPlanResp)
	err := c.cc.Invoke(ctx, PlanService_PING_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetHealth(ctx context.Context, in *GetHealthReq, opts ...grpc.CallOption) (*GetHealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResp)
	err := c.cc.Invoke(ctx, PlanService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanServiceServer is the server API for PlanService service.
// All implementations must embed UnimplementedPlanServiceServer
// for forward compatibility.
type PlanServiceServer interface {
	// plan_name, user_id -> exists, plan_id
	PlanExistsReturnId(context.Context, *SendPlanName) (*PlanExistsResp, error)
	// plan_name, user_id -> exits, plan_id, exercise_ids
	PlanExistsReturnPlan(context.Context, *SendPlanName) (*PlanExistsReturnPlanResp, error)
	// user_id -> empty_plan_id
	GetEmptyPlanId(context.Context, *SendUserID) (*EmptyPlanIdResp, error)
	// user_id -> msg
	CreateEmptyPlan(context.Context, *SendUserID) (*CreateEmptyPlanResp, error)
	// {} -> msg
	CheckHealth(context.Context, *CheckHealthReq) (*CheckHealthResp, error)
	// user_id, plan_name, exercises_names -> msg, plan_name, exercises_name
	CreatePlan(context.Context, *CreatePlanReq) (*CreatePlanResp, error)
	// user_id -> number_of_plans, [{plan_name, exercise_names}]
	GetAllPlans(context.Context, *GetAllPlansReq) (*GetAllPlansResp, error)
	// user_id, plan_name -> plan_name, exercise_names
	GetPlanByName(context.Context, *GetPlanByNameReq) (*GetPlanByNameResp, error)
	// user_id, plan_name, exercise_names -> plan_names, exercise_names
	AddExercisesToPlan(context.Context, *PlanReq) (*PlanResp, error)
	// user_id, plan_name, exercise_names -> plan_names, exercise_names
	DeleteExercisesFromPlan(context.Context, *PlanReq) (*PlanResp, error)
	// user_id, plan_name -> {}
	DeletePlan(context.Context, *DeletePlanReq) (*DeletePlanResp, error)
	PING(context.Context, *PingPlanReq) (*PingPlanResp, error)
	GetHealth(context.Context, *GetHealthReq) (*GetHealthResp, error)
	mustEmbedUnimplementedPlanServiceServer()
}

// UnimplementedPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanServiceServer struct{}

func (UnimplementedPlanServiceServer) PlanExistsReturnId(context.Context, *SendPlanName) (*PlanExistsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanExistsReturnId not implemented")
}
func (UnimplementedPlanServiceServer) PlanExistsReturnPlan(context.Context, *SendPlanName) (*PlanExistsReturnPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanExistsReturnPlan not implemented")
}
func (UnimplementedPlanServiceServer) GetEmptyPlanId(context.Context, *SendUserID) (*EmptyPlanIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmptyPlanId not implemented")
}
func (UnimplementedPlanServiceServer) CreateEmptyPlan(context.Context, *SendUserID) (*CreateEmptyPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmptyPlan not implemented")
}
func (UnimplementedPlanServiceServer) CheckHealth(context.Context, *CheckHealthReq) (*CheckHealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedPlanServiceServer) CreatePlan(context.Context, *CreatePlanReq) (*CreatePlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedPlanServiceServer) GetAllPlans(context.Context, *GetAllPlansReq) (*GetAllPlansResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPlans not implemented")
}
func (UnimplementedPlanServiceServer) GetPlanByName(context.Context, *GetPlanByNameReq) (*GetPlanByNameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanByName not implemented")
}
func (UnimplementedPlanServiceServer) AddExercisesToPlan(context.Context, *PlanReq) (*PlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExercisesToPlan not implemented")
}
func (UnimplementedPlanServiceServer) DeleteExercisesFromPlan(context.Context, *PlanReq) (*PlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExercisesFromPlan not implemented")
}
func (UnimplementedPlanServiceServer) DeletePlan(context.Context, *DeletePlanReq) (*DeletePlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlan not implemented")
}
func (UnimplementedPlanServiceServer) PING(context.Context, *PingPlanReq) (*PingPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PING not implemented")
}
func (UnimplementedPlanServiceServer) GetHealth(context.Context, *GetHealthReq) (*GetHealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedPlanServiceServer) mustEmbedUnimplementedPlanServiceServer() {}
func (UnimplementedPlanServiceServer) testEmbeddedByValue()                     {}

// UnsafePlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanServiceServer will
// result in compilation errors.
type UnsafePlanServiceServer interface {
	mustEmbedUnimplementedPlanServiceServer()
}

func RegisterPlanServiceServer(s grpc.ServiceRegistrar, srv PlanServiceServer) {
	// If the following call panics, it indicates UnimplementedPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanService_ServiceDesc, srv)
}

func _PlanService_PlanExistsReturnId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPlanName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).PlanExistsReturnId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_PlanExistsReturnId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).PlanExistsReturnId(ctx, req.(*SendPlanName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_PlanExistsReturnPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPlanName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).PlanExistsReturnPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_PlanExistsReturnPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).PlanExistsReturnPlan(ctx, req.(*SendPlanName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetEmptyPlanId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetEmptyPlanId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetEmptyPlanId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetEmptyPlanId(ctx, req.(*SendUserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_CreateEmptyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).CreateEmptyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_CreateEmptyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).CreateEmptyPlan(ctx, req.(*SendUserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).CheckHealth(ctx, req.(*CheckHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).CreatePlan(ctx, req.(*CreatePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetAllPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPlansReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetAllPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetAllPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetAllPlans(ctx, req.(*GetAllPlansReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetPlanByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetPlanByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetPlanByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetPlanByName(ctx, req.(*GetPlanByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_AddExercisesToPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).AddExercisesToPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_AddExercisesToPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).AddExercisesToPlan(ctx, req.(*PlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_DeleteExercisesFromPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).DeleteExercisesFromPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_DeleteExercisesFromPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).DeleteExercisesFromPlan(ctx, req.(*PlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_DeletePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).DeletePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_DeletePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).DeletePlan(ctx, req.(*DeletePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_PING_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).PING(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_PING_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).PING(ctx, req.(*PingPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetHealth(ctx, req.(*GetHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanService_ServiceDesc is the grpc.ServiceDesc for PlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plan.PlanService",
	HandlerType: (*PlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlanExistsReturnId",
			Handler:    _PlanService_PlanExistsReturnId_Handler,
		},
		{
			MethodName: "PlanExistsReturnPlan",
			Handler:    _PlanService_PlanExistsReturnPlan_Handler,
		},
		{
			MethodName: "GetEmptyPlanId",
			Handler:    _PlanService_GetEmptyPlanId_Handler,
		},
		{
			MethodName: "CreateEmptyPlan",
			Handler:    _PlanService_CreateEmptyPlan_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _PlanService_CheckHealth_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _PlanService_CreatePlan_Handler,
		},
		{
			MethodName: "GetAllPlans",
			Handler:    _PlanService_GetAllPlans_Handler,
		},
		{
			MethodName: "GetPlanByName",
			Handler:    _PlanService_GetPlanByName_Handler,
		},
		{
			MethodName: "AddExercisesToPlan",
			Handler:    _PlanService_AddExercisesToPlan_Handler,
		},
		{
			MethodName: "DeleteExercisesFromPlan",
			Handler:    _PlanService_DeleteExercisesFromPlan_Handler,
		},
		{
			MethodName: "DeletePlan",
			Handler:    _PlanService_DeletePlan_Handler,
		},
		{
			MethodName: "PING",
			Handler:    _PlanService_PING_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _PlanService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plan.proto",
}
