// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceName int32

const (
	ServiceName_ENUM_SERVICE_NAME_UNSPECIFIED ServiceName = 0
	ServiceName_PLAN_SERVICE                  ServiceName = 1
	ServiceName_AUTH_SERVICE                  ServiceName = 2
	ServiceName_TRACKER_SERVICE               ServiceName = 3
	ServiceName_EXERCISE_SERVICE              ServiceName = 4
	ServiceName_EMAIL_SERVICE                 ServiceName = 5
)

// Enum value maps for ServiceName.
var (
	ServiceName_name = map[int32]string{
		0: "ENUM_SERVICE_NAME_UNSPECIFIED",
		1: "PLAN_SERVICE",
		2: "AUTH_SERVICE",
		3: "TRACKER_SERVICE",
		4: "EXERCISE_SERVICE",
		5: "EMAIL_SERVICE",
	}
	ServiceName_value = map[string]int32{
		"ENUM_SERVICE_NAME_UNSPECIFIED": 0,
		"PLAN_SERVICE":                  1,
		"AUTH_SERVICE":                  2,
		"TRACKER_SERVICE":               3,
		"EXERCISE_SERVICE":              4,
		"EMAIL_SERVICE":                 5,
	}
)

func (x ServiceName) Enum() *ServiceName {
	p := new(ServiceName)
	*p = x
	return p
}

func (x ServiceName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceName) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (ServiceName) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x ServiceName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceName.Descriptor instead.
func (ServiceName) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_ENUM_TASK_STATUS_UNDEFINED TaskStatus = 0
	TaskStatus_TASK_COMPLETED             TaskStatus = 1
	TaskStatus_TASK_PENDING               TaskStatus = 2
	TaskStatus_TASK_NOT_COMPLETED         TaskStatus = 3
	TaskStatus_TASK_FAILED                TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "ENUM_TASK_STATUS_UNDEFINED",
		1: "TASK_COMPLETED",
		2: "TASK_PENDING",
		3: "TASK_NOT_COMPLETED",
		4: "TASK_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"ENUM_TASK_STATUS_UNDEFINED": 0,
		"TASK_COMPLETED":             1,
		"TASK_PENDING":               2,
		"TASK_NOT_COMPLETED":         3,
		"TASK_FAILED":                4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

type TaskName int32

const (
	TaskName_ENUM_TASK_NAME_UNDEFINED   TaskName = 0
	TaskName_CREATE_EMPTY_PLAN_FOR_USER TaskName = 1
	TaskName_SEND_EMAIL_FOR_SIGNING_UP  TaskName = 2
	TaskName_UPDATE_PLAN                TaskName = 3
)

// Enum value maps for TaskName.
var (
	TaskName_name = map[int32]string{
		0: "ENUM_TASK_NAME_UNDEFINED",
		1: "CREATE_EMPTY_PLAN_FOR_USER",
		2: "SEND_EMAIL_FOR_SIGNING_UP",
		3: "UPDATE_PLAN",
	}
	TaskName_value = map[string]int32{
		"ENUM_TASK_NAME_UNDEFINED":   0,
		"CREATE_EMPTY_PLAN_FOR_USER": 1,
		"SEND_EMAIL_FOR_SIGNING_UP":  2,
		"UPDATE_PLAN":                3,
	}
)

func (x TaskName) Enum() *TaskName {
	p := new(TaskName)
	*p = x
	return p
}

func (x TaskName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskName) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[2].Descriptor()
}

func (TaskName) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[2]
}

func (x TaskName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskName.Descriptor instead.
func (TaskName) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2}
}

type QueueName int32

const (
	QueueName_ENUM_QUEUE_NAME_UNDEFINED QueueName = 0
	QueueName_PLAN_QUEUE                QueueName = 1
	QueueName_RESULT_QUEUE              QueueName = 2
	QueueName_EMAIL_QUEUE               QueueName = 3
)

// Enum value maps for QueueName.
var (
	QueueName_name = map[int32]string{
		0: "ENUM_QUEUE_NAME_UNDEFINED",
		1: "PLAN_QUEUE",
		2: "RESULT_QUEUE",
		3: "EMAIL_QUEUE",
	}
	QueueName_value = map[string]int32{
		"ENUM_QUEUE_NAME_UNDEFINED": 0,
		"PLAN_QUEUE":                1,
		"RESULT_QUEUE":              2,
		"EMAIL_QUEUE":               3,
	}
)

func (x QueueName) Enum() *QueueName {
	p := new(QueueName)
	*p = x
	return p
}

func (x QueueName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueName) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[3].Descriptor()
}

func (QueueName) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[3]
}

func (x QueueName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueName.Descriptor instead.
func (QueueName) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{3}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto\x12\x04enum*\x92\x01\n" +
	"\vServiceName\x12!\n" +
	"\x1dENUM_SERVICE_NAME_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPLAN_SERVICE\x10\x01\x12\x10\n" +
	"\fAUTH_SERVICE\x10\x02\x12\x13\n" +
	"\x0fTRACKER_SERVICE\x10\x03\x12\x14\n" +
	"\x10EXERCISE_SERVICE\x10\x04\x12\x11\n" +
	"\rEMAIL_SERVICE\x10\x05*{\n" +
	"\n" +
	"TaskStatus\x12\x1e\n" +
	"\x1aENUM_TASK_STATUS_UNDEFINED\x10\x00\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x01\x12\x10\n" +
	"\fTASK_PENDING\x10\x02\x12\x16\n" +
	"\x12TASK_NOT_COMPLETED\x10\x03\x12\x0f\n" +
	"\vTASK_FAILED\x10\x04*x\n" +
	"\bTaskName\x12\x1c\n" +
	"\x18ENUM_TASK_NAME_UNDEFINED\x10\x00\x12\x1e\n" +
	"\x1aCREATE_EMPTY_PLAN_FOR_USER\x10\x01\x12\x1d\n" +
	"\x19SEND_EMAIL_FOR_SIGNING_UP\x10\x02\x12\x0f\n" +
	"\vUPDATE_PLAN\x10\x03*]\n" +
	"\tQueueName\x12\x1d\n" +
	"\x19ENUM_QUEUE_NAME_UNDEFINED\x10\x00\x12\x0e\n" +
	"\n" +
	"PLAN_QUEUE\x10\x01\x12\x10\n" +
	"\fRESULT_QUEUE\x10\x02\x12\x0f\n" +
	"\vEMAIL_QUEUE\x10\x03B\x0eZ\f/shared/enumb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_enum_proto_goTypes = []any{
	(ServiceName)(0), // 0: enum.ServiceName
	(TaskStatus)(0),  // 1: enum.TaskStatus
	(TaskName)(0),    // 2: enum.TaskName
	(QueueName)(0),   // 3: enum.QueueName
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
