// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tracker.proto

package tracker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackerService_StartEmptyWorkout_FullMethodName    = "/tracker.TrackerService/StartEmptyWorkout"
	TrackerService_StartWorkoutWithPlan_FullMethodName = "/tracker.TrackerService/StartWorkoutWithPlan"
	TrackerService_EndWorkout_FullMethodName           = "/tracker.TrackerService/EndWorkout"
	TrackerService_PING_FullMethodName                 = "/tracker.TrackerService/PING"
	TrackerService_GetHealth_FullMethodName            = "/tracker.TrackerService/GetHealth"
	TrackerService_CancelWorkout_FullMethodName        = "/tracker.TrackerService/CancelWorkout"
)

// TrackerServiceClient is the client API for TrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackerServiceClient interface {
	StartEmptyWorkout(ctx context.Context, in *StartEmptyWorkoutReq, opts ...grpc.CallOption) (*GeneralResp, error)
	StartWorkoutWithPlan(ctx context.Context, in *StartWorkoutWithPlanReq, opts ...grpc.CallOption) (*StartWorkoutWithPlanResp, error)
	EndWorkout(ctx context.Context, in *EndWorkoutReq, opts ...grpc.CallOption) (*EndWorkoutResp, error)
	PING(ctx context.Context, in *PingTrackReq, opts ...grpc.CallOption) (*PingTrackResp, error)
	GetHealth(ctx context.Context, in *GetHealthReq, opts ...grpc.CallOption) (*GetHealthResp, error)
	CancelWorkout(ctx context.Context, in *CancelWorkoutReq, opts ...grpc.CallOption) (*CancelWorkoutResp, error)
}

type trackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackerServiceClient(cc grpc.ClientConnInterface) TrackerServiceClient {
	return &trackerServiceClient{cc}
}

func (c *trackerServiceClient) StartEmptyWorkout(ctx context.Context, in *StartEmptyWorkoutReq, opts ...grpc.CallOption) (*GeneralResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResp)
	err := c.cc.Invoke(ctx, TrackerService_StartEmptyWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) StartWorkoutWithPlan(ctx context.Context, in *StartWorkoutWithPlanReq, opts ...grpc.CallOption) (*StartWorkoutWithPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkoutWithPlanResp)
	err := c.cc.Invoke(ctx, TrackerService_StartWorkoutWithPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) EndWorkout(ctx context.Context, in *EndWorkoutReq, opts ...grpc.CallOption) (*EndWorkoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndWorkoutResp)
	err := c.cc.Invoke(ctx, TrackerService_EndWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) PING(ctx context.Context, in *PingTrackReq, opts ...grpc.CallOption) (*PingTrackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingTrackResp)
	err := c.cc.Invoke(ctx, TrackerService_PING_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) GetHealth(ctx context.Context, in *GetHealthReq, opts ...grpc.CallOption) (*GetHealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResp)
	err := c.cc.Invoke(ctx, TrackerService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) CancelWorkout(ctx context.Context, in *CancelWorkoutReq, opts ...grpc.CallOption) (*CancelWorkoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWorkoutResp)
	err := c.cc.Invoke(ctx, TrackerService_CancelWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackerServiceServer is the server API for TrackerService service.
// All implementations must embed UnimplementedTrackerServiceServer
// for forward compatibility.
type TrackerServiceServer interface {
	StartEmptyWorkout(context.Context, *StartEmptyWorkoutReq) (*GeneralResp, error)
	StartWorkoutWithPlan(context.Context, *StartWorkoutWithPlanReq) (*StartWorkoutWithPlanResp, error)
	EndWorkout(context.Context, *EndWorkoutReq) (*EndWorkoutResp, error)
	PING(context.Context, *PingTrackReq) (*PingTrackResp, error)
	GetHealth(context.Context, *GetHealthReq) (*GetHealthResp, error)
	CancelWorkout(context.Context, *CancelWorkoutReq) (*CancelWorkoutResp, error)
	mustEmbedUnimplementedTrackerServiceServer()
}

// UnimplementedTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackerServiceServer struct{}

func (UnimplementedTrackerServiceServer) StartEmptyWorkout(context.Context, *StartEmptyWorkoutReq) (*GeneralResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartEmptyWorkout not implemented")
}
func (UnimplementedTrackerServiceServer) StartWorkoutWithPlan(context.Context, *StartWorkoutWithPlanReq) (*StartWorkoutWithPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkoutWithPlan not implemented")
}
func (UnimplementedTrackerServiceServer) EndWorkout(context.Context, *EndWorkoutReq) (*EndWorkoutResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EndWorkout not implemented")
}
func (UnimplementedTrackerServiceServer) PING(context.Context, *PingTrackReq) (*PingTrackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PING not implemented")
}
func (UnimplementedTrackerServiceServer) GetHealth(context.Context, *GetHealthReq) (*GetHealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedTrackerServiceServer) CancelWorkout(context.Context, *CancelWorkoutReq) (*CancelWorkoutResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelWorkout not implemented")
}
func (UnimplementedTrackerServiceServer) mustEmbedUnimplementedTrackerServiceServer() {}
func (UnimplementedTrackerServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackerServiceServer will
// result in compilation errors.
type UnsafeTrackerServiceServer interface {
	mustEmbedUnimplementedTrackerServiceServer()
}

func RegisterTrackerServiceServer(s grpc.ServiceRegistrar, srv TrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackerService_ServiceDesc, srv)
}

func _TrackerService_StartEmptyWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEmptyWorkoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).StartEmptyWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_StartEmptyWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).StartEmptyWorkout(ctx, req.(*StartEmptyWorkoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_StartWorkoutWithPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkoutWithPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).StartWorkoutWithPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_StartWorkoutWithPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).StartWorkoutWithPlan(ctx, req.(*StartWorkoutWithPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_EndWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndWorkoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).EndWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_EndWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).EndWorkout(ctx, req.(*EndWorkoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_PING_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingTrackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).PING(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_PING_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).PING(ctx, req.(*PingTrackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).GetHealth(ctx, req.(*GetHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_CancelWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).CancelWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_CancelWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).CancelWorkout(ctx, req.(*CancelWorkoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackerService_ServiceDesc is the grpc.ServiceDesc for TrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracker.TrackerService",
	HandlerType: (*TrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartEmptyWorkout",
			Handler:    _TrackerService_StartEmptyWorkout_Handler,
		},
		{
			MethodName: "StartWorkoutWithPlan",
			Handler:    _TrackerService_StartWorkoutWithPlan_Handler,
		},
		{
			MethodName: "EndWorkout",
			Handler:    _TrackerService_EndWorkout_Handler,
		},
		{
			MethodName: "PING",
			Handler:    _TrackerService_PING_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _TrackerService_GetHealth_Handler,
		},
		{
			MethodName: "CancelWorkout",
			Handler:    _TrackerService_CancelWorkout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracker.proto",
}
